module.exports = [
    {
        "title": "The Bloody Chamber and Other Stories",
        "isbn": "9781784878689",
        "description": "A celebrated collection of dark, imaginative retellings of classic fairy tales exploring power, desire and identity.",
        "price": "14.99",
        "publication_year": 2018,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/bloody-chamber-and-other-stories.jpg",
        "publisherName": "Vintage Classics"
    },
    {
        "title": "Walden: Life in the Woods",
        "isbn": "9781423646792",
        "description": "Henry David Thoreau's timeless reflections on simple living, nature and self-reliance.",
        "price": "18.99",
        "publication_year": 2017,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/walden-life-in-the-woods-life.jpg",
        "publisherName": "Gibbs M. Smith Inc"
    },
    {
        "title": "Tess of the d'Urbervilles",
        "isbn": "9780141040332",
        "description": "Thomas Hardy's tragic masterpiece following Tess as she struggles against fate and Victorian society.",
        "price": "10.99",
        "publication_year": 2003,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 18,
        "cover_image_url": "images/books/tess-of-the-d-urbervilles.jpg",
        "publisherName": "Penguin Classics"
    },
    {
        "title": "Great Expectations",
        "isbn": "9780141198897",
        "description": "Charles Dickens' coming-of-age classic about ambition, love and redemption.",
        "price": "9.99",
        "publication_year": 2012,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 25,
        "cover_image_url": "images/books/great-expectations.jpg",
        "publisherName": "Penguin Classics"
    },
    {
        "title": "Honey",
        "isbn": "9780008759773",
        "description": "A contemporary coming-of-age novel exploring identity, family and belonging.",
        "price": "16.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/honey.jpg",
        "publisherName": "Farshore"
    },
    {
        "title": "The Impossible Fortune",
        "isbn": "9781405975735",
        "description": "The latest mystery featuring the Thursday Murder Club, filled with humour, suspense and unforgettable characters.",
        "price": "22.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/impossible-fortune.jpg",
        "publisherName": "Penguin Classics"
    },
    {
        "title": "Hooked",
        "isbn": "9780008753832",
        "description": "A gripping literary novel inspired by Japanese folklore and contemporary life.",
        "price": "17.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/hooked.jpg",
        "publisherName": "Fourth Estate Ltd"
    },
    {
        "title": "Slow Gods",
        "isbn": "9780356526201",
        "description": "A sweeping space opera exploring humanity, technology and distant civilizations.",
        "price": "22.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/slow-gods.jpg",
        "publisherName": "Orbit"
    },
    {
        "title": "The Martian",
        "isbn": "9781785031137",
        "description": "An astronaut stranded on Mars must rely on science and ingenuity to survive.",
        "price": "10.99",
        "publication_year": 2014,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 25,
        "cover_image_url": "images/books/martian.jpg",
        "publisherName": "Del Rey"
    },
    {
        "title": "Dracula",
        "isbn": "9781914602948",
        "description": "Bram Stoker's legendary Gothic horror novel introducing one of literature's most enduring vampires.",
        "price": "20.00",
        "publication_year": 2023,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 18,
        "cover_image_url": "images/books/dracula.jpg",
        "publisherName": "Chiltern Publishing"
    },
    {
        "title": "The Psychology of Money",
        "isbn": "9780857197689",
        "description": "A bestselling exploration of how behaviour, emotions and decision-making shape financial success more than technical knowledge or intelligence.",
        "price": "14.99",
        "publication_year": 2020,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/psychology-of-money.jpg",
        "publisherName": "Harriman House Publishing"
    },
    {
        "title": "Heartburn",
        "isbn": "9780349010359",
        "description": "Nora Ephron's witty semi-autobiographical novel blending humour, relationships and personal resilience into a timeless modern classic.",
        "price": "10.99",
        "publication_year": 2023,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 18,
        "cover_image_url": "images/books/heartburn.jpg",
        "publisherName": "Virago Press Ltd"
    },
    {
        "title": "The Hitler Years: Holocaust",
        "isbn": "9781035912483",
        "description": "An extensively researched account of the Holocaust during the Nazi era, examining policies, events and the human impact of one of history's darkest periods.",
        "price": "30.00",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 12,
        "cover_image_url": "images/books/hitler-years-holocaust.jpg",
        "publisherName": "Apollo"
    },
    {
        "title": "How to Stay Sane in an Age of Division",
        "isbn": "9781788165723",
        "description": "A thoughtful manifesto encouraging empathy, critical thinking and hope during times of political and social division.",
        "price": "9.99",
        "publication_year": 2020,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/how-to-stay-sane.jpg",
        "publisherName": "Wellcome Collection"
    },
    {
        "title": "Anam Cara: Spiritual Wisdom from the Celtic World",
        "isbn": "9781804992548",
        "description": "A reflective exploration of Celtic spirituality, friendship and personal growth through timeless wisdom and poetic storytelling.",
        "price": "16.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 15,
        "cover_image_url": "images/books/anam-cara.jpg",
        "publisherName": "Penguin Business"
    },
    {
        "title": "Migratory Birds",
        "isbn": "9781945492525",
        "description": "A thoughtful exploration of migration, borders and identity, combining personal narrative with social and political reflection.",
        "price": "17.99",
        "publication_year": 2020,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 15,
        "cover_image_url": "images/books/migratory-birds.jpg",
        "publisherName": "Transit Books"
    },
    {
        "title": "Decolonising the University",
        "isbn": "9780745338200",
        "description": "An important collection examining higher education through the perspectives of race, equality and decolonisation.",
        "price": "21.99",
        "publication_year": 2018,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 12,
        "cover_image_url": "images/books/decolonising-the-university.jpg",
        "publisherName": "Pluto Press"
    },
    {
        "title": "Breaking the Grass Ceiling: The History of the Women's Football Association",
        "isbn": "9781803996202",
        "description": "The fascinating history of the Women's Football Association and the pioneers who helped shape the modern women's game.",
        "price": "18.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 12,
        "cover_image_url": "images/books/breaking-the-grass-ceiling.jpg",
        "publisherName": "The History Press Ltd"
    },
    {
        "title": "Football She Wrote: An Anthology of Women's Writing on the Game",
        "isbn": "9781838030025",
        "description": "A diverse anthology celebrating women's voices, experiences and perspectives on football from writers across the sport.",
        "price": "16.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 15,
        "cover_image_url": "images/books/football-she-wrote.jpg",
        "publisherName": "Floodlit Dreams Ltd"
    },
    {
        "title": "The Land and Its People",
        "isbn": "9781408714126",
        "description": "David Sedaris reflects on travel, culture and everyday life with his signature wit, humour and sharp observations.",
        "price": "22.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 10,
        "cover_image_url": "images/books/land-and-its-people.jpg",
        "publisherName": "Abacus"
    },
    {
        "title": "Firefly",
        "isbn": "9781917044523",
        "description": "A beautifully illustrated picture book celebrating the mystery and wonder of the natural world after dark, encouraging children to explore nature with curiosity and imagination.",
        "price": "16.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/firefly.jpg",
        "publisherName": "Magic Cat Publishing"
    },
    {
        "title": "Cottonopolis",
        "isbn": "9781915179395",
        "description": "An exciting middle-grade adventure combining mystery, friendship and history in a richly imagined industrial city.",
        "price": "9.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/cottonopolis.jpg",
        "publisherName": "Northodox Press"
    },
    {
        "title": "Keedie",
        "isbn": "9781913311988",
        "description": "A heartfelt novel exploring friendship, family and neurodiversity through memorable characters and an inspiring story.",
        "price": "8.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 18,
        "cover_image_url": "images/books/keedie.jpg",
        "publisherName": "Knights Of Media"
    },
    {
        "title": "Gordon: The Meanest Goose on Earth",
        "isbn": "9780192788658",
        "description": "A humorous picture book about kindness, friendship and learning that everyone deserves a second chance.",
        "price": "7.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/gordon-goose.jpg",
        "publisherName": "Oxford University Press"
    },
    {
        "title": "A Buffalo Named Brave",
        "isbn": "9780008762322",
        "description": "A touching picture book helping young readers develop confidence, resilience and emotional wellbeing through an engaging animal story.",
        "price": "12.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/buffalo-named-brave.jpg",
        "publisherName": "Farshore"
    },
    {
        "title": "The Big Book of Nature Art",
        "isbn": "9780500652930",
        "description": "An inspiring activity book filled with creative nature-based art projects that encourage children to explore the outdoors through drawing, painting and crafts.",
        "price": "18.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/big-book-of-nature-art.jpg",
        "publisherName": "Thames & Hudson Ltd"
    },
    {
        "title": "The Queen in the Cave",
        "isbn": "9781406367430",
        "description": "A beautifully illustrated picture book about courage, imagination and discovering the strength to face the unknown.",
        "price": "13.99",
        "publication_year": 2023,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/queen-in-the-cave.jpg",
        "publisherName": "Walker Studio"
    },
    {
        "title": "How to Make a Story",
        "isbn": "9780192779045",
        "description": "A fun and imaginative picture book encouraging children to create their own stories while learning about storytelling and creativity.",
        "price": "7.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/how-to-make-a-story.jpg",
        "publisherName": "Oxford University Press"
    },
    {
        "title": "Collage Workshop for Kids",
        "isbn": "9781631595202",
        "description": "A creative activity book introducing children to collage techniques through colourful projects inspired by the Eric Carle Museum.",
        "price": "19.99",
        "publication_year": 2018,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 12,
        "cover_image_url": "images/books/collage-workshop-for-kids.jpg",
        "publisherName": "Quarry Books"
    },
    {
        "title": "The Whale That Sings in the Deep",
        "isbn": "9780192782656",
        "description": "A beautifully illustrated story celebrating marine life, friendship and the importance of protecting our oceans.",
        "price": "14.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 18,
        "cover_image_url": "images/books/whale-that-sings-in-the-deep.jpg",
        "publisherName": "Oxford University Press"
    },
    {
        "title": "Life in the UK Test: Study Guide 2026",
        "isbn": "9781907389986",
        "description": "The official study guide designed to help candidates prepare for the British citizenship and Life in the UK test with clear explanations and practice material.",
        "price": "14.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/life-in-the-uk-test-study-guide-2026.jpg",
        "publisherName": "Red Squirrel Publishing"
    },
    {
        "title": "Stop Making Stupid Investments",
        "isbn": "9781394377657",
        "description": "David Leiter explains how investors can avoid common financial mistakes, ignore market hype and build long-term wealth using practical investment principles.",
        "price": "24.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 15,
        "cover_image_url": "images/books/stop-making-stupid-investments.jpg",
        "publisherName": "John Wiley & Sons Inc"
    },
    {
        "title": "Investing to Save the Planet",
        "isbn": "9780241457238",
        "description": "A practical guide showing how personal investments can support environmental sustainability while building long-term financial returns.",
        "price": "15.99",
        "publication_year": 2023,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 18,
        "cover_image_url": "images/books/investing-to-save-the-planet.jpg",
        "publisherName": "Penguin Business"
    },
    {
        "title": "The Little Book of Common Sense Investing",
        "isbn": "9781119404507",
        "description": "John C. Bogle presents a straightforward investment strategy based on low-cost index funds and long-term investing for consistent financial success.",
        "price": "19.99",
        "publication_year": 2017,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/the-little-book-of-common-sense-investing.jpg",
        "publisherName": "John Wiley & Sons Inc"
    },
    {
        "title": "The Intelligent Fund Investor",
        "isbn": "9780857198761",
        "description": "Joe Wiggins explains how to evaluate investment funds, reduce costly mistakes and make better long-term investment decisions.",
        "price": "18.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 16,
        "cover_image_url": "images/books/the-intelligent-fund-investor.jpg",
        "publisherName": "Harriman House Publishing"
    },
    {
        "title": "You Are a Badass at Making Money",
        "isbn": "9781473649569",
        "description": "Jen Sincero shares practical advice and motivational strategies to help readers transform their mindset about money, overcome limiting beliefs and build lasting financial confidence.",
        "price": "14.99",
        "publication_year": 2018,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/you-are-a-badass-at-making-money.jpg",
        "publisherName": "John Murray One"
    },
    {
        "title": "Think and Grow Rich",
        "isbn": "9781785042416",
        "description": "One of the most influential personal finance classics, teaching timeless principles of success, wealth creation and personal achievement.",
        "price": "10.99",
        "publication_year": 2018,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 25,
        "cover_image_url": "images/books/think-and-grow-rich.jpg",
        "publisherName": "Vermilion"
    },
    {
        "title": "Femonomics",
        "isbn": "9781399737609",
        "description": "Corinne Low explores how economic thinking can improve everyday decision-making, careers and financial wellbeing while highlighting the role of data in achieving gender equality.",
        "price": "22.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 12,
        "cover_image_url": "images/books/femonomics.jpg",
        "publisherName": "Hodder & Stoughton"
    },
    {
        "title": "Black's Law Dictionary (11th Edition)",
        "isbn": "9781539229759",
        "description": "The definitive legal dictionary trusted by lawyers, judges and students, containing thousands of legal definitions, terms and references.",
        "price": "59.99",
        "publication_year": 2019,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 8,
        "cover_image_url": "images/books/blacks-law-dictionary.jpg",
        "publisherName": "John Murray One"
    },
    {
        "title": "Rich Dad's Guide to Investing",
        "isbn": "9781612680217",
        "description": "Robert T. Kiyosaki explains the investing principles used by wealthy individuals and provides practical guidance for building long-term financial independence.",
        "price": "16.99",
        "publication_year": 2014,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 18,
        "cover_image_url": "images/books/rich-dads-guide-to-investing.jpg",
        "publisherName": "Plata Publishing"
    },
    {
        "title": "The Body: A Guide for Occupants",
        "isbn": "9780857522405",
        "description": "Bill Bryson explores the extraordinary human body with his trademark humour and curiosity, explaining how our bodies function through fascinating scientific discoveries.",
        "price": "14.99",
        "publication_year": 2019,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/the-body-a-guide-for-occupants.jpg",
        "publisherName": "Wellcome Collection"
    },
    {
        "title": "This Is Going to Hurt",
        "isbn": "9781509858637",
        "description": "A bestselling memoir from former junior doctor Adam Kay, offering an honest, moving and often hilarious insight into life inside the NHS.",
        "price": "10.99",
        "publication_year": 2018,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 25,
        "cover_image_url": "images/books/this-is-going-to-hurt.jpg",
        "publisherName": "Picador"
    },
    {
        "title": "Oxford Handbook of Clinical Medicine",
        "isbn": "9780198867609",
        "description": "One of the most trusted medical reference books, providing concise guidance on clinical practice, diagnosis and patient care.",
        "price": "39.99",
        "publication_year": 2023,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 12,
        "cover_image_url": "images/books/oxford-handbook-of-clinical-medicine.jpg",
        "publisherName": "Oxford University Press"
    },
    {
        "title": "Infectious: Pathogens and How We Fight Them",
        "isbn": "9780861542314",
        "description": "Professor John Tregoning explains how viruses, bacteria and the immune system interact, offering an accessible introduction to infectious diseases and vaccines.",
        "price": "16.99",
        "publication_year": 2023,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 15,
        "cover_image_url": "images/books/infectious-pathogens-and-how-we-fight-them.jpg",
        "publisherName": "Hodder & Stoughton"
    },
    {
        "title": "The Top 100 Drugs",
        "isbn": "9780702081545",
        "description": "A practical prescribing guide covering the most commonly used medicines, their clinical applications and safe prescribing principles.",
        "price": "34.99",
        "publication_year": 2021,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 10,
        "cover_image_url": "images/books/the-top-100-drugs.jpg",
        "publisherName": "Thames & Hudson Ltd"
    },
    {
        "title": "Blind Spots",
        "isbn": "9781637744178",
        "description": "Dr. Marty Makary examines weaknesses within modern healthcare and proposes practical solutions to improve patient safety and medical decision-making.",
        "price": "19.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 12,
        "cover_image_url": "images/books/blind-spots.jpg",
        "publisherName": "Northodox Press"
    },
    {
        "title": "Life on a Knife's Edge",
        "isbn": "9780241488515",
        "description": "Neurosurgeon Rahul Jandial shares remarkable stories from the operating theatre while exploring the science, ethics and humanity behind brain surgery.",
        "price": "15.99",
        "publication_year": 2022,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 18,
        "cover_image_url": "images/books/life-on-a-knifes-edge.jpg",
        "publisherName": "Fourth Estate Ltd"
    },
    {
        "title": "Dragonfly Falling",
        "isbn": "9780230739581",
        "description": "The second novel in Adrian Tchaikovsky's acclaimed Shadows of the Apt fantasy series, continuing the epic war between empires with unforgettable characters and imaginative world-building.",
        "price": "8.99",
        "publication_year": 2010,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/dragonfly-falling.jpg",
        "publisherName": "Tor"
    },
    {
        "title": "What We Can Know",
        "isbn": "9781529959215",
        "description": "Ian McEwan explores science, truth and human understanding in a thought-provoking work examining the limits and possibilities of knowledge.",
        "price": "12.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/what-we-can-know.jpg",
        "publisherName": "Vintage Digital"
    },
    {
        "title": "The Names",
        "isbn": "9781399624053",
        "description": "Florence Knapp's acclaimed debut novel explores identity, memory and family through beautifully written literary fiction.",
        "price": "11.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/the-names.jpg",
        "publisherName": "Phoenix"
    },
    {
        "title": "No Friend to This House",
        "isbn": "9781529061574",
        "description": "Natalie Haynes retells a timeless Greek myth with wit, compassion and dramatic storytelling, bringing classical characters vividly to life.",
        "price": "10.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/no-friend-to-this-house.jpg",
        "publisherName": "Mantle"
    },
    {
        "title": "This Way Up",
        "isbn": "9780008710309",
        "description": "Map Men explain the fascinating history of maps, cartography and geographical mistakes in an entertaining and informative exploration of how maps shape our understanding of the world.",
        "price": "11.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/this-way-up.jpg",
        "publisherName": "Mudlark"
    },
    {
        "title": "Tomato: 80 Recipes Celebrating the Extraordinary Tomato",
        "isbn": "9781787137868",
        "description": "Claire Thomson presents eighty creative recipes celebrating one of the world's most versatile ingredients, from simple everyday meals to impressive seasonal dishes.",
        "price": "13.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/tomato-80-recipes.jpg",
        "publisherName": "Quadrille"
    },
    {
        "title": "Book Lovers",
        "isbn": "9780241995358",
        "description": "Emily Henry's bestselling romantic comedy follows two rivals whose unexpected holiday encounters challenge everything they thought they wanted from life and love.",
        "price": "9.99",
        "publication_year": 2022,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/book-lovers.jpg",
        "publisherName": "Penguin Classics"
    },
    {
        "title": "The Mercy Step",
        "isbn": "9781913175757",
        "description": "Marcia Hutchinson tells a compelling story of resilience, justice and hope through memorable characters facing difficult personal and social challenges.",
        "price": "9.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/the-mercy-step.jpg",
        "publisherName": "Floodlit Dreams Ltd"
    },
    {
        "title": "My Father's House",
        "isbn": "9781473560000",
        "description": "Joseph O'Connor's bestselling historical novel tells the remarkable true story of courage and resistance in Nazi-occupied Rome during the Second World War.",
        "price": "10.99",
        "publication_year": 2023,
        "book_language": "English",
        "format": "E-books",
        "stock_quantity": 999,
        "cover_image_url": "images/books/my-fathers-house.jpg",
        "publisherName": "Vintage Digital"
    },
    {
        "title": "Infinite Crisis Omnibus (2020 Edition)",
        "isbn": "9781779503442",
        "description": "A massive collection of DC's landmark Infinite Crisis event, bringing together Earth's greatest heroes in an epic battle that reshaped the DC Universe.",
        "price": "125.00",
        "publication_year": 2020,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 8,
        "cover_image_url": "images/books/infinite-crisis-omnibus.jpg",
        "publisherName": "DC Comics"
    },
    {
        "title": "Identity Crisis: 20th Anniversary Deluxe Edition",
        "isbn": "9781779527493",
        "description": "A modern DC Comics classic exploring mystery, loss and the hidden secrets of the Justice League.",
        "price": "39.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 12,
        "cover_image_url": "images/books/identity-crisis-deluxe.jpg",
        "publisherName": "DC Comics"
    },
    {
        "title": "Knight Terrors Omnibus",
        "isbn": "9781799501091",
        "description": "Collecting the complete Knight Terrors crossover event featuring Batman, Superman and the DC Universe facing their darkest nightmares.",
        "price": "150.00",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 6,
        "cover_image_url": "images/books/knight-terrors-omnibus.jpg",
        "publisherName": "DC Comics"
    },
    {
        "title": "Dark Nights: Metal – Dark Knights Rising",
        "isbn": "9781401277329",
        "description": "The Dark Multiverse unleashes terrifying new versions of Batman in this companion volume to Dark Nights: Metal.",
        "price": "24.99",
        "publication_year": 2018,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 15,
        "cover_image_url": "images/books/dark-knights-rising.jpg",
        "publisherName": "DC Comics"
    },
    {
        "title": "The Absolute Multiversity",
        "isbn": "9781779525994",
        "description": "Grant Morrison's ambitious exploration of the DC Multiverse presented in a deluxe Absolute Edition with oversized artwork.",
        "price": "110.00",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Hardcover",
        "stock_quantity": 7,
        "cover_image_url": "images/books/the-absolute-multiversity.jpg",
        "publisherName": "DC Comics"
    },
    {
        "title": "Ben 10 #2",
        "isbn": "72513036343502011",
        "description": "The second issue of the Ben 10 comic series featuring exciting adventures with Ben Tennyson and the Omnitrix.",
        "price": "4.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Comic",
        "stock_quantity": 25,
        "cover_image_url": "images/books/ben-10-2.jpg",
        "publisherName": "DYNAMITE Entertainment"
    },
    {
        "title": "Marvel/DC: Spider-Man/Superman #1",
        "isbn": "75960621395500111",
        "description": "An exciting crossover bringing together Spider-Man and Superman in a story written by Brad Meltzer.",
        "price": "6.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Comic",
        "stock_quantity": 30,
        "cover_image_url": "images/books/spiderman-superman-1.jpg",
        "publisherName": "Marvel"
    },
    {
        "title": "Absolute Batman #20",
        "isbn": "76194138584602011",
        "description": "Batman continues his fight against Gotham's greatest threats in this latest issue of the acclaimed Absolute Batman series.",
        "price": "5.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Comic",
        "stock_quantity": 40,
        "cover_image_url": "images/books/absolute-batman-20.jpg",
        "publisherName": "DC Comics"
    },
    {
        "title": "Avengers: Armageddon #1",
        "isbn": "75960621563800111",
        "description": "The Avengers face a devastating new threat in the opening chapter of Marvel's Armageddon storyline.",
        "price": "5.99",
        "publication_year": 2025,
        "book_language": "English",
        "format": "Comic",
        "stock_quantity": 40,
        "cover_image_url": "images/books/avengers-armageddon-1.jpg",
        "publisherName": "Marvel"
    },
    {
        "title": "Eloquent JavaScript (4th Edition)",
        "isbn": "9781593279509",
        "description": "A modern introduction to JavaScript covering programming fundamentals, browser development and advanced concepts through practical examples and exercises.",
        "price": "34.99",
        "publication_year": 2024,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 20,
        "cover_image_url": "images/books/eloquent-javascript-4th-edition.jpg",
        "publisherName": "No Starch Press"
    },
    {
        "title": "Python Crash Course (3rd Edition)",
        "isbn": "9781718502703",
        "description": "A hands-on introduction to Python programming that guides beginners from the fundamentals to creating practical projects and applications.",
        "price": "39.99",
        "publication_year": 2023,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 18,
        "cover_image_url": "images/books/python-crash-course-3rd-edition.jpg",
        "publisherName": "No Starch Press"
    },
    {
        "title": "Automate the Boring Stuff with Python (2nd Edition)",
        "isbn": "9781593279929",
        "description": "Learn Python by automating repetitive tasks including file management, spreadsheets, web scraping and everyday office work.",
        "price": "37.99",
        "publication_year": 2020,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 16,
        "cover_image_url": "images/books/automate-the-boring-stuff-with-python-2nd-edition.jpg",
        "publisherName": "No Starch Press"
    },
    {
        "title": "Clean Code",
        "isbn": "9780132350884",
        "description": "One of the most influential software engineering books ever written, teaching principles and best practices for writing readable, maintainable and professional code.",
        "price": "44.99",
        "publication_year": 2008,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 25,
        "cover_image_url": "images/books/clean-code.jpg",
        "publisherName": "Pearson"
    },
    {
        "title": "JavaScript: The Definitive Guide (7th Edition)",
        "isbn": "9781491952023",
        "description": "A comprehensive reference covering the JavaScript language, modern web APIs and best practices for professional web development.",
        "price": "54.99",
        "publication_year": 2020,
        "book_language": "English",
        "format": "Paperback",
        "stock_quantity": 15,
        "cover_image_url": "images/books/javascript-the-definitive-guide-7th-edition.jpg",
        "publisherName": "O'Reilly Media"
    }
];
